name: CI/CD Pipeline for Chrome Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Lint Code
      - name: Lint Code
        run: npx eslint "src/**/*.{ts,js}" "tests/**/*.{ts,js}"

      # Build Extension
      - name: Build Chrome Extension
        run: npm run build

      # Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-dist
          path: dist/
